# Import libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
path = os.getcwd()

In [3]:
metadata = pd.read_excel(path+'/Data/'+'metadata.xlsx',sheet_name = 1)
imodulon_annotations = pd.read_excel(path+'/Data/'+'imodulon_annotations.xlsx',sheet_name=0)

In [4]:
microarray_metadata = metadata[(metadata['Dataset']=='MA-1') | (metadata['Dataset']=='MA-2')  | (metadata['Dataset']=='MA-3')]
microarray_metadata

,Sample ID,Dataset,Low Quality?,NCBI GEO ID,Proteomexchange ID,PMID,DOI,Genotype,Platform,Reference Conditions
362,dinI___U_N0025_r1,MA-1,NaN,GSE6836,NaN,17214507.0,NaN,Escherichia coli K-12 MG1655 dinI overexpression,Affymetrix E. coli Antisense Genome Array,"WT_N0000_r1, WT_N0000_r2"
363,dinI___U_N0025_r2,MA-1,NaN,GSE6836,NaN,17214507.0,NaN,Escherichia coli K-12 MG1655 dinI overexpression,Affymetrix E. coli Antisense Genome Array,"WT_N0000_r1, WT_N0000_r2"
364,dinI___U_N0025_r3,MA-1,NaN,GSE6836,NaN,17214507.0,NaN,Escherichia coli K-12 MG1655 dinI overexpression,Affymetrix E. coli Antisense Genome Array,"WT_N0000_r1, WT_N0000_r2"
365,dinP___U_N0025_r1,MA-1,NaN,GSE6836,NaN,17214507.0,NaN,Escherichia coli K-12 MG1655 dinB overexpression,Affymetrix E. coli Antisense Genome Array,"WT_N0000_r1, WT_N0000_r2"
366,dinP___U_N0025_r2,MA-1,NaN,GSE6836,NaN,17214507.0,NaN,Escherichia coli K-12 MG1655 dinB overexpression,Affymetrix E. coli Antisense Genome Array,"WT_N0000_r1, WT_N0000_r2"
...,...,...,...,...,...,...,...,...,...,...
827,ec_carbon__propylene_glycol__2,MA-3,NaN,GSE34631,NaN,22936779.0,NaN,Escherichia coli K-12 MG1655 Evolved,Affymetrix E. coli Genome 2.0 Array,"ec_diffexp__glucose__1, ec_diffexp__glucose__1..."
828,ec_carbon__propylene_glycol__3,MA-3,NaN,GSE34631,NaN,22936779.0,NaN,Escherichia coli K-12 MG1655 Evolved,Affymetrix E. coli Genome 2.0 Array,"ec_diffexp__glucose__1, ec_diffexp__glucose__1..."
829,ec_carbon__glycerol__1,MA-3,NaN,GSE34631,NaN,22936779.0,NaN,Escherichia coli K-12 MG1655 Evolved,Affymetrix E. coli Genome 2.0 Array,"ec_diffexp__glucose__1, ec_diffexp__glucose__1..."
830,ec_carbon__glycerol__2,MA-3,NaN,GSE34631,NaN,22936779.0,NaN,Escherichia coli K-12 MG1655 Evolved,Affymetrix E. coli Genome 2.0 Array,"ec_diffexp__glucose__1, ec_diffexp__glucose__1..."
831,ec_carbon__glycerol__3,MA-3,NaN,GSE34631,NaN,22936779.0,NaN,Escherichia coli K-12 MG1655 Evolved,Affymetrix E. coli Genome 2.0 Array,"ec_diffexp__glucose__1, ec_diffexp__glucose__1..."

In [5]:
microarray_activity_1 = pd.read_excel(path+'/Data/'+'activities.xlsx',sheet_name = 3,index_col='Unnamed: 0')
microarray_activity_2 = pd.read_excel(path+'/Data/'+'activities.xlsx',sheet_name = 4,index_col='Unnamed: 0')
microarray_activity_3 = pd.read_excel(path+'/Data/'+'activities.xlsx',sheet_name = 5,index_col='Unnamed: 0')


controls_1 = []
controls_2 = []
controls_3 = []

for column in microarray_activity_1.columns:
    if('N0000' in column):
        controls_1.append(column)
        
for column in microarray_activity_2.columns:
    if('aero' in column and 'anaero' not in column):
        controls_2.append(column)
        
for column in microarray_activity_3.columns:
    if('glucose' in column):
        controls_3.append(column)

In [6]:
microarray_activity_1[controls_1]

,luc___U_N0000_r1,luc___U_N0000_r2,luc___U_N0000_r3,WT_N0000_r1,WT_N0000_r2,recA_D_N0000_r1,recA_D_N0000_r2,luc2_U_N0000_r1,luc2_U_N0000_r2,T24_N0000_r1,T24_N0000_r2,T24_N0000_r3,T60_N0000_r1,T60_N0000_r2,T60_N0000_r3
0,2.671930,3.852709,3.048215,-0.333251,0.333251,7.959939,7.180933,0.065074,5.053451,10.883192,10.637041,10.578746,11.253835,10.583485,10.304958
1,-1.265047,-0.353250,0.281566,0.278167,-0.278167,1.100125,1.753724,-0.459719,0.024386,0.848822,1.179357,0.525351,0.684147,0.596320,0.456648
2,1.067460,1.138336,1.572258,-0.247980,0.247980,0.771643,-0.246365,0.514387,0.916328,1.140911,1.092510,1.263718,0.822955,1.280875,0.939503
3,-4.867149,-3.887617,-0.903719,-0.204666,0.204666,3.285857,3.480443,-5.317663,-1.873336,4.963474,4.936504,4.733038,5.323375,5.529462,5.365292
4,0.610437,0.707880,-0.016491,0.300796,-0.300796,0.317434,0.245202,0.163691,0.451935,0.622736,0.458056,0.604086,-0.138689,-0.116964,-0.070377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,1.187961,1.561764,0.959688,2.708192,-2.708192,0.396185,0.108689,3.180981,2.082271,0.566109,0.523251,-2.630526,-0.198991,0.171230,-0.398265
99,11.151126,9.955097,11.590247,-0.836704,0.836704,11.097645,8.564005,1.600611,8.065263,10.646310,10.732601,10.681757,10.879185,10.123451,11.033115
100,-2.360205,-2.079673,-2.229470,0.021187,-0.021187,-1.543769,-2.253978,-1.670352,-3.451375,-1.547359,-1.877618,-1.322774,-1.513874,-1.347581,-0.999502
101,-13.013775,-9.351402,-6.879305,0.850800,-0.850800,-0.931181,0.937770,-4.932467,-5.028803,-10.515693,-9.763797,-10.614705,-6.197888,-5.622218,-6.059596
102,7.185679,7.425507,5.140695,-0.163869,0.163869,5.134770,4.351714,3.012014,4.221196,4.498472,4.322384,4.259073,3.495726,3.057391,3.529896

In [7]:
variances_MA1 = microarray_activity_1[controls_1].var(axis=1).sort_values(ascending = False)
variances_MA2 = microarray_activity_2[controls_2].var(axis=1).sort_values(ascending = False)
variances_MA3 = microarray_activity_3[controls_3].var(axis=1).sort_values(ascending = False)

In [8]:
variances_MA1

32     83.477658
11     47.432634
5      32.123239
0      19.309107
101    19.022783
         ...
42      0.135229
41      0.108433
4       0.104628
90      0.103850
20      0.077278
Length: 103, dtype: float64

In [21]:
imodulon_annotations[imodulon_annotations['Dataset']=='MA-1'].loc[143+5,:]

I-modulon Name                                               MA-1_5
Dataset                                                        MA-1
Component                                                         5
Class                                                    regulatory
Description                                                    rpoS
P-value                                                         0.0
q-value                                                         0.0
Precision                                                  0.493827
Recall                                                     0.136054
F1-score                                                   0.213333
Curated?                                                        NaN
Genes             amyA,bcsC,bfr,blc,bolA,curA,dkgA,dps,elaB,fbaB...
Name: 148, dtype: object